from setuptools import setup, find_packages

setup(name='brutefit',
      version='0.0.1',
      description='Tools for finding an arbitrary multivariate polynomial that best fits some data.',
      url='https://github.com/oscarbranson/brutefit',
      author='Oscar Branson',
      author_email='oscarbranson@gmail.com',
      license='MIT',
      packages=find_packages(),
      keywords=['science', 'data', 'empiricism'],
      classifiers=['Development Status :: 4 - Beta',
                   'Intended Audience :: Science/Research',
                   'Programming Language :: Python :: 3 :: Only',
                   ],
      install_requires=['numpy',
                        'sklearn',
                        'pandas',
                        'sympy',
                        'tqdm'],
      # package_data={'cbsyst': ['test_data/*']},
      zip_safe=True)
